spring:
  config:
    import:
      - classpath:application-sec.yml
      - classpath:application-db.yml
  thymeleaf:
    cache: false

server:
  port: 8888
  error:
    include-stacktrace: never

finance:
  news:
    url: https://www.hankyung.com/economy
  market:
    url: https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=0&ie=utf8&query=%EB%84%A4%EC%9D%B4%EB%B2%84%EC%A6%9D%EA%B6%8C
    korea: KOSPI, KOSDAQ, KOSPI GLOVAL
    crypto: CRYPTO
  csv:
    path: assets/data_0138_20231106_utf8.csv


view:
  sign-up: /view/sign-up
  root: /